# prog_l  wr_decay  wr_nearby  n_prog  depth  count  cheating

[[plot]]
query = """ select * from distplot """
[plot.config]
x = "cnt"
y = "rowid"
color = "mut"

[[plot]]
query = """ select * from hb2 """
[plot.config]
x = "time"
y = "reward"
facet_row = "campaign_id"

[[plot]]
query = """ select * from history_binned """
[plot.config]
x = "time"
y = "reward"
color = "val"

[[plot]]
query = """
select avg(value) val, avg(reward) reward, avg(time) time, campaign_id
from history_power_of_two
group by ceil(reward*100), ceil(time/3)
order by random()
limit 50000 ;
"""
[plot.config]
x = "time"
y = "reward"
color = "campaign_id"
# facet_row = "campaign_id"

[[plot]]
query = """
select value, reward, time, campaign_id
from history_power_of_two
order by random()
limit 5000 ;
"""
[plot.config]
x = "time"
y = "reward"
color = "campaign_id"
# facet_row = "wr_decay"
