# prog_l  wr_decay  wr_nearby  n_prog  depth  count  cheating
[[plot]]
query = """
select value, reward, time, campaign_id
from history_power_of_two
order by random()
limit 5000 ;
"""
[plot.config]
x = "time"
y = "reward"
color = "campaign_id"
# facet_row = "wr_decay"
