
# prog_l  wr_decay  wr_nearby  n_prog  depth  count  cheating
[[plot]]
query = """
select depth, count as count, prog_l, wr_decay from wiring where wr_nearby = 1 and cheating = 0
UNION ALL
select depth, count as count, prog_l, 'zero' as wr_decay from wiring where wr_nearby = 0 and cheating = 0
order by wr_decay, depth
"""
[plot.config]
x = "depth"
y = "count"
color = "prog_l"
facet_row = "wr_decay"

## use on curiosity db's
[[plot]]
query = """
select * from vali_scores
"""
[plot.config]
x = "i_epoch"
y = "mse"
color = "class_id"

[[plot]]
query = """
with A as (select value, reward * 1e7 + 1e7 as reward, log2(time+1)+random()/3 logtime, log2(value + 1e-8) as log2val from history_powerOfTwo)
select * from A
--where logtime < 1 and reward < 0.1
"""
[plot.config]
x = "logtime"
y = "reward"
color = "log2val"




